### PR TITLE
Shannonioffe/fixed click code header when no code

### PR DESCRIPTION
**Pull request by shanioffe**
added ng-if to text

### CODE REVIEW

**Review by EVogel1999 — CHANGES_REQUESTED** [review]
For the ```Copy of Web Pages``` directory those don't need to be updated.  I'm honestly not sure why that directory exists.  You'll also want to change the branch to ```main``` instead of ```master```.

**Comment by shanioffe** [comment]
> For the `Copy of Web Pages` directory those don't need to be updated. I'm honestly not sure why that directory exists. You'll also want to change the branch to `main` instead of `master`.

Okay I changed the branch to main which took out the extra changes and left just the one that I made.

**Review by EVogel1999 — APPROVED** [review]
Looks good!  Thank you!

**Review by pmanal1 — APPROVED** [review]

**Review by JosueMolinaMorales — APPROVED** [review]
Looks good

**Review by mfranz1 — APPROVED** [review]

**Review by AStoerkel1 — APPROVED** [review]

**Review by pzalep1 — APPROVED** [review]

**Pull request merged**
